import {
  DEFAULT_STATUS_PAGE_THEME_ID,
  isLegacyStatusPageTemplateCss,
  resolveStatusPageTheme,
} from '@/lib/status-pages/theme-contract';

/**
 * Older gallery CSS was stored wholesale in branding.customCss. Some persisted payloads can lose
 * the leading `/* Template: ... *\/` marker during migrations/edits while retaining the distinctive
 * template structure. Detect that structure conservatively so curated themes do not inherit stale
 * `!important` light-card rules.
 */
function looksLikeLegacyStatusPageTemplateCss(value: string): boolean {
  const importantCount = value.match(/!important\b/gi)?.length ?? 0;
  if (importantCount < 3) return false;

  const hasServiceCard = value.includes('.status-service-card');
  const hasContainer = value.includes('.status-page-container');
  const hasLegacyChrome =
    value.includes('.status-page-header') ||
    value.includes('#incidents .status-incident-card') ||
    value.includes('form button[type="submit"]') ||
    value.includes("form button[type='submit']");

  return hasServiceCard && hasContainer && hasLegacyChrome;
}

/**
 * Identifies CSS generated by the retired legacy template gallery.
 *
 * Kept as a small exported predicate so the Design UI can explain why a legacy payload is ignored
 * instead of silently making a curated theme look broken.
 */
export function isLegacyStatusPageCustomCss(value: unknown): boolean {
  if (typeof value !== 'string' || !value.trim()) return false;
  return isLegacyStatusPageTemplateCss(value) || looksLikeLegacyStatusPageTemplateCss(value);
}

/**
 * Resolve the Advanced CSS that may reach the public renderer and the live preview.
 *
 * The native Default theme deliberately preserves every historical custom CSS payload for backwards
 * compatibility. Curated themes suppress only positively identified old gallery templates because
 * those payloads contain broad `!important` light-surface rules that can defeat the curated theme.
 * Genuine customer-authored Advanced CSS remains the final override layer for every theme.
 */
export function resolveStatusPageCustomCss(themeId: unknown, value: unknown): string {
  if (typeof value !== 'string') return '';

  const selectedTheme = resolveStatusPageTheme(themeId);
  if (
    selectedTheme.id !== DEFAULT_STATUS_PAGE_THEME_ID &&
    isLegacyStatusPageCustomCss(value)
  ) {
    return '';
  }

  return value;
}
