-- Add RUNBOOK to JobType
ALTER TYPE "JobType" ADD VALUE 'RUNBOOK';

-- Add RUNBOOK types to AuditEntityType
ALTER TYPE "AuditEntityType" ADD VALUE 'RUNBOOK';
ALTER TYPE "AuditEntityType" ADD VALUE 'RUNBOOK_VERSION';
ALTER TYPE "AuditEntityType" ADD VALUE 'RUNBOOK_EXECUTION';
ALTER TYPE "AuditEntityType" ADD VALUE 'RUNBOOK_AGENT';
ALTER TYPE "AuditEntityType" ADD VALUE 'RUNBOOK_AGENT_POOL';
ALTER TYPE "AuditEntityType" ADD VALUE 'RUNBOOK_SECRET';

-- Add RUNBOOK types to IncidentEventType
ALTER TYPE "IncidentEventType" ADD VALUE 'RUNBOOK_SUGGESTED';
ALTER TYPE "IncidentEventType" ADD VALUE 'RUNBOOK_STARTED';
ALTER TYPE "IncidentEventType" ADD VALUE 'RUNBOOK_STEP_COMPLETED';
ALTER TYPE "IncidentEventType" ADD VALUE 'RUNBOOK_APPROVAL_REQUIRED';
ALTER TYPE "IncidentEventType" ADD VALUE 'RUNBOOK_APPROVED';
ALTER TYPE "IncidentEventType" ADD VALUE 'RUNBOOK_COMPLETED';
ALTER TYPE "IncidentEventType" ADD VALUE 'RUNBOOK_FAILED';
ALTER TYPE "IncidentEventType" ADD VALUE 'RUNBOOK_CANCELLED';
