import 'server-only';

import crypto from 'crypto';
import JSZip from 'jszip';
import { AppError } from '@/lib/errors/app-error';
import * as domains from './domains';
import * as serializers from './serializers';
import { assertNoSecretLikeKeys } from './redaction';
import { buildManifest, type ExportDomainSummary } from './manifest';

export interface GenerateSubjectExportInput {
  requestId: string;
  subjectType: string;
  subjectId: string;
}

export interface GeneratedExport {
  buffer: Buffer;
  checksum: string;
  sizeBytes: number;
}

const README = `This archive is a data subject access export generated by OpsKnight.

- manifest.json describes exactly what is (and is not) included and why.
- Security credentials (passwords, tokens, API keys, encrypted secrets) are
  never included in this or any OpsKnight export.
- Each other file corresponds to one category of the subject's own direct
  data relations. Empty arrays mean no records were found in that category,
  not that the category was skipped.
`;

/**
 * The only sanctioned way to produce a subject export. Fetches, serializes,
 * and defense-in-depth-checks each domain before zipping, so a bug in one
 * serializer cannot silently ship a credential.
 */
export async function generateSubjectExport(
  input: GenerateSubjectExportInput
): Promise<GeneratedExport> {
  if (input.subjectType !== 'USER') {
    throw new AppError({
      code: 'VALIDATION_FAILED',
      userMessage: 'Automated export is only available for USER subjects in this release.',
    });
  }

  const userId = input.subjectId;
  const [
    profile,
    identities,
    memberships,
    incidents,
    incidentNotes,
    schedules,
    notifications,
    auditEvents,
  ] = await Promise.all([
    domains.fetchProfile(userId),
    domains.fetchIdentities(userId),
    domains.fetchMemberships(userId),
    domains.fetchIncidents(userId),
    domains.fetchIncidentNotes(userId),
    domains.fetchSchedules(userId),
    domains.fetchNotifications(userId),
    domains.fetchAuditEvents(userId),
  ]);

  if (!profile) {
    throw new AppError({
      code: 'RESOURCE_NOT_FOUND',
      userMessage: 'The export subject could not be found.',
    });
  }

  const files: Record<string, unknown> = {
    'profile.json': serializers.serializeProfile(profile),
    'identities.json': serializers.serializeIdentities(identities),
    'memberships.json': serializers.serializeMemberships(memberships),
    'incidents.json': serializers.serializeIncidents(incidents),
    'incident-notes.json': serializers.serializeIncidentNotes(incidentNotes),
    'schedules.json': serializers.serializeSchedules(schedules),
    'notifications.json': serializers.serializeNotifications(notifications),
    'audit-events.json': serializers.serializeAuditEvents(auditEvents),
  };

  for (const [name, content] of Object.entries(files)) {
    assertNoSecretLikeKeys(content, name);
  }

  const domainSummary: ExportDomainSummary[] = [
    {
      domain: 'identities',
      exportedCount: identities.length,
      totalCount: identities.length,
      truncated: false,
    },
    {
      domain: 'memberships',
      exportedCount: memberships.length,
      totalCount: memberships.length,
      truncated: false,
    },
    {
      domain: 'incidents',
      exportedCount: incidents.length,
      totalCount: incidents.length,
      truncated: false,
    },
    {
      domain: 'incident-notes',
      exportedCount: incidentNotes.length,
      totalCount: incidentNotes.length,
      truncated: false,
    },
    {
      domain: 'schedules',
      exportedCount: schedules.shifts.length + schedules.overrides.length,
      totalCount: schedules.shifts.length + schedules.overrides.length,
      truncated: false,
    },
    {
      domain: 'notifications',
      exportedCount: notifications.items.length,
      totalCount: notifications.totalCount,
      truncated: notifications.truncated,
    },
    {
      domain: 'audit-events',
      exportedCount: auditEvents.items.length,
      totalCount: auditEvents.totalCount,
      truncated: auditEvents.truncated,
    },
  ];

  const manifest = buildManifest({
    requestId: input.requestId,
    subjectType: input.subjectType,
    subjectId: input.subjectId,
    generatedAt: new Date(),
    domainSummary,
  });

  const zip = new JSZip();
  zip.file('manifest.json', JSON.stringify(manifest, null, 2));
  zip.file('README.txt', README);
  for (const [name, content] of Object.entries(files)) {
    zip.file(name, JSON.stringify(content, null, 2));
  }

  const buffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
  const checksum = crypto.createHash('sha256').update(buffer).digest('hex');

  return { buffer, checksum, sizeBytes: buffer.byteLength };
}
