ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'API_KEY';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'SSO_CONFIG';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'SCHEDULE';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'CUSTOM_FIELD';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'STATUS_PAGE';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'SYSTEM_CONFIG';
