apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../split
  - pgbouncer-configmap.yaml
  - pgbouncer-secret.yaml
  - pgbouncer-deployment.yaml
  - pgbouncer-service.yaml
  - pgbouncer-pdb.yaml
  - pgbouncer-network-policy.yaml

patches:
  - path: web-database-patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: opsknight-app-netpol
    patch: |-
      - op: replace
        path: /spec/egress/0
        value:
          to:
            - podSelector:
                matchLabels:
                  app: opsknight-pgbouncer
          ports:
            - protocol: TCP
              port: 6432
      - op: add
        path: /spec/egress/1
        value:
          to:
            - podSelector:
                matchLabels:
                  app: opsknight-postgres
          ports:
            - protocol: TCP
              port: 5432
