apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../split
  - pgbouncer-configmap.yaml
  - pgbouncer-secret.yaml
  - pgbouncer-deployment.yaml
  - pgbouncer-service.yaml

patches:
  - path: web-database-patch.yaml
