apiVersion: v1
kind: Service
metadata:
  name: opsknight-pgbouncer
  namespace: opsknight
  labels:
    app: opsknight-pgbouncer
spec:
  type: ClusterIP
  selector:
    app: opsknight-pgbouncer
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: pgbouncer
