/** Authoritative lifecycle disposition for every direct Prisma User relationship. */
export const USER_REFERENCE_POLICY = {
  assignedIncidents: { deactivate: 'REPORT', delete: 'BLOCK' },
  teamMemberships: { deactivate: 'REPORT', delete: 'BLOCK' },
  onCallShifts: { deactivate: 'REPORT', delete: 'BLOCK' },
  escalationRules: { deactivate: 'REPORT', delete: 'BLOCK' },
  incidentNotes: { deactivate: 'KEEP', delete: 'SET_NULL' },
  postmortems: { deactivate: 'KEEP', delete: 'SET_NULL' },
  notifications: { deactivate: 'KEEP', delete: 'SET_NULL' },
  notificationEndpoints: { deactivate: 'SUPPRESS', delete: 'CASCADE' },
  inAppNotifications: { deactivate: 'SUPPRESS', delete: 'CASCADE' },
  devices: { deactivate: 'REVOKE', delete: 'CASCADE' },
  incidentWatchers: { deactivate: 'SUPPRESS', delete: 'CASCADE' },
  auditLogs: { deactivate: 'KEEP', delete: 'SET_NULL' },
  overrides: { deactivate: 'REPORT', delete: 'BLOCK' },
  overrideReplacements: { deactivate: 'REPORT', delete: 'BLOCK' },
  layerAssignments: { deactivate: 'REPORT', delete: 'BLOCK' },
  apiKeys: { deactivate: 'REVOKE', delete: 'CASCADE' },
  incidentTemplates: { deactivate: 'KEEP', delete: 'CASCADE' },
  updatedProviders: { deactivate: 'KEEP', delete: 'SET_NULL' },
  teamsLed: { deactivate: 'REPORT', delete: 'BLOCK' },
  slackIntegrations: { deactivate: 'KEEP', delete: 'SET_NULL' },
  slackOAuthConfigs: { deactivate: 'KEEP', delete: 'SET_NULL' },
  slackDestinations: { deactivate: 'KEEP', delete: 'SET_NULL' },
  jiraConfigsUpdated: { deactivate: 'KEEP', delete: 'SET_NULL' },
  microsoftTeamsConfigs: { deactivate: 'KEEP', delete: 'SET_NULL' },
  microsoftTeamsInstallations: { deactivate: 'KEEP', delete: 'SET_NULL' },
  microsoftTeamsDestinations: { deactivate: 'KEEP', delete: 'SET_NULL' },
  // Preserve the room's provider-side membership/audit projection when an
  // OpsKnight account is removed; Prisma clears only the local user link.
  warRoomParticipants: { deactivate: 'KEEP', delete: 'SET_NULL' },
  chatIdentityLinks: { deactivate: 'DENY_AUTH', delete: 'CASCADE' },
  oidcConfigs: { deactivate: 'KEEP', delete: 'CASCADE' },
  oidcIdentities: { deactivate: 'DENY_AUTH', delete: 'CASCADE' },
  oidcLinkingApproval: { deactivate: 'REVOKE', delete: 'CASCADE' },
  avatar: { deactivate: 'KEEP', delete: 'CASCADE' },
  dashboards: { deactivate: 'REPORT', delete: 'BLOCK' },
  assignedActionItems: { deactivate: 'REPORT', delete: 'BLOCK' },
  tokens: { deactivate: 'REVOKE', delete: 'SET_NULL' },
  privacyRequestsAssigned: { deactivate: 'KEEP', delete: 'SET_NULL' },
  privacyRequestsRequested: { deactivate: 'KEEP', delete: 'SET_NULL' },
  privacyRequestsVerified: { deactivate: 'KEEP', delete: 'SET_NULL' },
  createdRetentionHolds: { deactivate: 'KEEP', delete: 'SET_NULL' },
  releasedRetentionHolds: { deactivate: 'KEEP', delete: 'SET_NULL' },
  initiatedEncryptionRuns: { deactivate: 'KEEP', delete: 'SET_NULL' },
} as const;

export type UserReferenceName = keyof typeof USER_REFERENCE_POLICY;
