apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - service-account.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
