-- AlterEnum
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'COMPLIANCE_DRIFT_EVENT';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'COMPLIANCE_MONITORING_RUN';

-- AlterEnum
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'COMPLIANCE_EVALUATION_SWEEP';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'COMPLIANCE_DRIFT_PROJECT';
