{{- if and .Values.pgbouncer.enabled (not .Values.pgbouncer.existingAuthSecret) }}
{{- $username := .Values.postgresql.username | replace "\\" "\\\\" | replace "\"" "\\\"" -}}
{{- $password := .Values.postgresql.password | replace "\\" "\\\\" | replace "\"" "\\\"" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsknight.pgbouncer.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: {{ include "opsknight.name" . }}-pgbouncer
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  userlist.txt: |
    "{{ $username }}" "{{ $password }}"
{{- end }}
