{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsknight.secretName" . }}
  labels:
    {{- include "opsknight.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.keys.databaseUrl }}: {{ include "opsknight.databaseUrl" . | b64enc | quote }}
  {{ .Values.secrets.keys.nextauthSecret }}: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
  {{ .Values.secrets.keys.apiKeySecret }}: {{ .Values.secrets.apiKeySecret | b64enc | quote }}
  {{ .Values.secrets.keys.encryptionKey }}: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  {{ .Values.secrets.keys.postgresUser }}: {{ .Values.postgresql.username | b64enc | quote }}
  {{ .Values.secrets.keys.postgresPassword }}: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}
