apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - runtime-deployments.yaml
  - runtime-pdbs.yaml
  - web-hpa.yaml
  - worker-network-policies.yaml

patches:
  - path: remove-integrated-pdb.yaml
  - path: web-service.yaml
  - path: web-network-policy.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: opsknight-app-netpol
    patch: |-
      - op: add
        path: /spec/ingress/1/from/0/podSelector/matchLabels/opsknight-role
        value: web
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: opsknight-(web|scheduler|general-worker|critical-worker|bulk-worker|status-projector)
    patch: |-
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
