export type ErrorCategory =
  | 'authentication'
  | 'authorization'
  | 'validation'
  | 'not_found'
  | 'conflict'
  | 'rate_limit'
  | 'dependency'
  | 'network'
  | 'internal';

export type ErrorExposure = 'public' | 'authenticated' | 'internal';

export type ErrorDefinition = {
  status: number;
  category: ErrorCategory;
  userMessage: string;
  action?: string;
  retryable?: boolean;
  exposure?: ErrorExposure;
};

export const ERROR_REGISTRY = {
  INTERNAL_ERROR: {
    status: 500,
    category: 'internal',
    userMessage:
      'An unexpected error occurred. Please try again. If the problem persists, contact support.',
    action: 'Try again. If the problem continues, contact support.',
    retryable: true,
    exposure: 'internal',
  },
  VALIDATION_FAILED: {
    status: 400,
    category: 'validation',
    userMessage: 'Please check your input and try again.',
    retryable: false,
    exposure: 'public',
  },
  INVALID_JSON: {
    status: 400,
    category: 'validation',
    userMessage: 'The request body contains invalid JSON.',
    action: 'Correct the request body and try again.',
    retryable: false,
    exposure: 'public',
  },
  PAYLOAD_TOO_LARGE: {
    status: 413,
    category: 'validation',
    userMessage: 'The request payload is too large.',
    action: 'Reduce the payload size and try again.',
    retryable: false,
    exposure: 'public',
  },
  AUTHENTICATION_REQUIRED: {
    status: 401,
    category: 'authentication',
    userMessage: 'Authentication is required to continue.',
    action: 'Sign in and try again.',
    retryable: false,
    exposure: 'public',
  },
  API_KEY_INVALID: {
    status: 401,
    category: 'authentication',
    userMessage: 'The API key is missing or invalid.',
    action: 'Provide a valid API key and try again.',
    retryable: false,
    exposure: 'public',
  },
  API_KEY_USER_INVALID: {
    status: 401,
    category: 'authentication',
    userMessage: 'The API key owner is no longer available.',
    action: 'Create or use an API key for an active user.',
    retryable: false,
    exposure: 'public',
  },
  API_SCOPE_REQUIRED: {
    status: 403,
    category: 'authorization',
    userMessage: 'The API key does not include the required scope.',
    action: 'Use an API key with the required scope.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_KEY_INVALID: {
    status: 403,
    category: 'authorization',
    userMessage: 'The integration key is invalid.',
    action: 'Verify the integration key and try again.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_DISABLED: {
    status: 403,
    category: 'authorization',
    userMessage: 'This integration is disabled.',
    action: 'Enable the integration before sending events.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested integration could not be found.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_AUTHENTICATION_FAILED: {
    status: 401,
    category: 'authentication',
    userMessage: 'Integration authentication failed.',
    action: 'Verify the integration credentials and try again.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_SIGNATURE_INVALID: {
    status: 401,
    category: 'authentication',
    userMessage: 'Webhook signature verification failed.',
    action: 'Verify the webhook signing secret and signature.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_SIGNATURE_MISSING: {
    status: 401,
    category: 'authentication',
    userMessage: 'A required webhook signature is missing.',
    action: 'Send the required signature header.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_TIMESTAMP_EXPIRED: {
    status: 401,
    category: 'authentication',
    userMessage: 'The webhook timestamp is outside the allowed window.',
    action: 'Send a fresh webhook request.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_PAYLOAD_INVALID: {
    status: 400,
    category: 'validation',
    userMessage: 'The integration payload is invalid.',
    action: 'Correct the payload and try again.',
    retryable: false,
    exposure: 'public',
  },
  INTEGRATION_VALIDATION_FAILED: {
    status: 400,
    category: 'validation',
    userMessage: 'The integration payload failed validation.',
    action: 'Correct the payload fields and try again.',
    retryable: false,
    exposure: 'public',
  },
  SESSION_REVOKED: {
    status: 401,
    category: 'authentication',
    userMessage: 'Your session is no longer valid.',
    action: 'Sign in again to continue.',
    retryable: false,
    exposure: 'public',
  },
  USER_DISABLED: {
    status: 403,
    category: 'authorization',
    userMessage: 'Your account is disabled.',
    action: 'Contact an administrator if you believe this is an error.',
    retryable: false,
    exposure: 'public',
  },
  AUTHORIZATION_DENIED: {
    status: 403,
    category: 'authorization',
    userMessage: 'You do not have permission to perform this action.',
    action: 'Contact an administrator if you believe you should have access.',
    retryable: false,
    exposure: 'public',
  },
  RESOURCE_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested item could not be found.',
    retryable: false,
    exposure: 'public',
  },
  RATE_LIMIT_EXCEEDED: {
    status: 429,
    category: 'rate_limit',
    userMessage: 'Too many requests were received.',
    action: 'Wait briefly before trying again.',
    retryable: true,
    exposure: 'public',
  },
  IDEMPOTENCY_KEY_INVALID: {
    status: 400,
    category: 'validation',
    userMessage: 'The idempotency key is invalid.',
    action: 'Provide a non-empty Idempotency-Key of 200 characters or fewer.',
    retryable: false,
    exposure: 'public',
  },
  IDEMPOTENCY_KEY_CONFLICT: {
    status: 409,
    category: 'conflict',
    userMessage: 'This idempotency key was already used for a different request.',
    action: 'Use a new Idempotency-Key for a different request payload.',
    retryable: false,
    exposure: 'public',
  },
  INCIDENT_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested incident could not be found.',
    retryable: false,
    exposure: 'public',
  },
  INCIDENT_ACCESS_DENIED: {
    status: 403,
    category: 'authorization',
    userMessage: 'You do not have permission to access this incident.',
    retryable: false,
    exposure: 'public',
  },
  INCIDENT_MODIFY_DENIED: {
    status: 403,
    category: 'authorization',
    userMessage: 'You do not have permission to modify this incident.',
    retryable: false,
    exposure: 'public',
  },
  INCIDENT_CREATE_SERVICE_ACCESS_DENIED: {
    status: 403,
    category: 'authorization',
    userMessage: 'You can only create incidents for services your team can access.',
    retryable: false,
    exposure: 'public',
  },
  INCIDENT_REQUIRED_FIELDS_MISSING: {
    status: 422,
    category: 'validation',
    userMessage: 'Some required incident information is missing.',
    action: 'Complete the required fields and try again.',
    retryable: false,
    exposure: 'public',
  },
  INCIDENT_TRANSITION_CONFLICT: {
    status: 409,
    category: 'conflict',
    userMessage: 'The incident status changed before this action completed.',
    action: 'Refresh the incident and try again.',
    retryable: true,
    exposure: 'public',
  },
  INCIDENT_STATE_CONFLICT: {
    status: 409,
    category: 'conflict',
    userMessage: 'The incident state changed before this action completed.',
    action: 'Refresh the incident and try again.',
    retryable: true,
    exposure: 'public',
  },
  STATUS_PAGE_STALE: {
    status: 409,
    category: 'conflict',
    userMessage: 'This status page was updated by another administrator.',
    action: 'Reload the page and apply your changes again.',
    retryable: true,
    exposure: 'authenticated',
  },
  INCIDENT_INVALID_TRANSITION: {
    status: 409,
    category: 'conflict',
    userMessage: 'This incident status change is not allowed from the current state.',
    action: 'Refresh the incident and choose a valid action.',
    retryable: false,
    exposure: 'public',
  },
  INCIDENT_INVALID_ARGUMENT: {
    status: 400,
    category: 'validation',
    userMessage: 'The incident update contains invalid input.',
    retryable: false,
    exposure: 'public',
  },
  SERVICE_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested service could not be found.',
    retryable: false,
    exposure: 'public',
  },
  SERVICE_ACCESS_DENIED: {
    status: 403,
    category: 'authorization',
    userMessage: 'You do not have access to this service.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested schedule could not be found.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_ACCESS_DENIED: {
    status: 403,
    category: 'authorization',
    userMessage: 'You do not have permission to access this schedule.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_OVERRIDE_ACCESS_DENIED: {
    status: 403,
    category: 'authorization',
    userMessage: 'You do not have permission to create an override for this schedule.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_NAME_CONFLICT: {
    status: 409,
    category: 'conflict',
    userMessage: 'A schedule with that name already exists.',
    action: 'Choose a different schedule name.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_LAYER_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested schedule layer could not be found.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_OVERRIDE_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested schedule override could not be found.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_LAYER_USER_DUPLICATE: {
    status: 409,
    category: 'conflict',
    userMessage: 'This responder is already assigned to this schedule.',
    action: 'Remove the existing assignment before adding another.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_RESPONDER_NOT_ACTIVE: {
    status: 409,
    category: 'conflict',
    userMessage: 'This responder is not active and cannot be assigned to an on-call schedule.',
    action: 'Activate the responder or choose an active responder.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_OVERRIDE_CONFLICT: {
    status: 409,
    category: 'conflict',
    userMessage: 'This override conflicts with an existing override for the same coverage period.',
    action: 'Choose a non-overlapping period or remove the existing override first.',
    retryable: false,
    exposure: 'public',
  },
  SCHEDULE_IN_USE: {
    status: 409,
    category: 'conflict',
    userMessage:
      'Cannot delete schedule because it is currently in use by one or more escalation policies.',
    action: 'Remove this schedule from all escalation policy steps before deleting it.',
    retryable: false,
    exposure: 'public',
  },
  STATUS_PAGE_WEBHOOK_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested status-page webhook could not be found.',
    retryable: false,
    exposure: 'public',
  },
  NOTIFICATION_PROVIDER_UNAVAILABLE: {
    status: 503,
    category: 'dependency',
    userMessage: 'The notification provider is temporarily unavailable.',
    action: 'Try again shortly.',
    retryable: true,
    exposure: 'public',
  },
  /** Control-plane DB failure: concurrency/quota query failed. Distinct from real saturation. */
  NOTIFICATION_CONTROL_PLANE_UNAVAILABLE: {
    status: 503,
    category: 'dependency',
    userMessage: 'The notification control plane is temporarily unavailable.',
    action: 'The system will retry delivery automatically.',
    retryable: true,
    exposure: 'internal',
  },
  PUSH_NO_SUBSCRIPTION: {
    status: 400,
    category: 'validation',
    userMessage: 'No active push subscription found for this device.',
    action: 'Enable push notifications on this device and try again.',
    retryable: false,
    exposure: 'public',
  },
  PUSH_SUBSCRIPTION_EXPIRED: {
    status: 410,
    category: 'validation',
    userMessage: 'The push subscription for this device has expired.',
    action: 'Re-enable push notifications on this device.',
    retryable: false,
    exposure: 'public',
  },
  PUSH_PERMISSION_REVOKED: {
    status: 403,
    category: 'authorization',
    userMessage: 'Push notification permission has been revoked for this device.',
    action: 'Re-enable push notifications in your browser or device settings.',
    retryable: false,
    exposure: 'public',
  },
  PUSH_VAPID_NOT_CONFIGURED: {
    status: 503,
    category: 'dependency',
    userMessage: 'Push notifications are not configured on this server.',
    action: 'Contact your administrator to configure VAPID keys.',
    retryable: false,
    exposure: 'public',
  },
  PUSH_VAPID_REJECTED: {
    status: 502,
    category: 'dependency',
    userMessage: 'The push server rejected the server credentials.',
    action: 'Contact your administrator to reconfigure VAPID keys.',
    retryable: false,
    exposure: 'public',
  },
  PUSH_PROVIDER_RATE_LIMITED: {
    status: 429,
    category: 'rate_limit',
    userMessage: 'Push delivery is temporarily rate-limited.',
    action: 'The system will retry delivery automatically.',
    retryable: true,
    exposure: 'public',
  },
  PUSH_PROVIDER_UNAVAILABLE: {
    status: 503,
    category: 'dependency',
    userMessage: 'The push notification provider is temporarily unavailable.',
    action: 'The system will retry delivery automatically.',
    retryable: true,
    exposure: 'public',
  },
  PUSH_NETWORK_FAILURE: {
    status: 503,
    category: 'dependency',
    userMessage: 'A network error occurred while delivering the push notification.',
    action: 'The system will retry delivery automatically.',
    retryable: true,
    exposure: 'public',
  },
  PUSH_DELIVERY_TIMEOUT: {
    status: 504,
    category: 'dependency',
    userMessage: 'Push delivery timed out.',
    action: 'The system will retry delivery automatically.',
    retryable: true,
    exposure: 'public',
  },
  PUSH_SERVER_CAPACITY: {
    status: 503,
    category: 'dependency',
    userMessage: 'The push provider is at capacity.',
    action: 'The system will retry delivery automatically.',
    retryable: true,
    exposure: 'public',
  },
  PUSH_DELIVERY_PARTIAL: {
    status: 207,
    category: 'dependency',
    userMessage: 'Push notification delivered to some but not all devices.',
    retryable: false,
    exposure: 'public',
  },
  PRIVACY_REQUEST_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested privacy request could not be found.',
    retryable: false,
    exposure: 'public',
  },
  PRIVACY_REQUEST_INVALID_TRANSITION: {
    status: 409,
    category: 'conflict',
    userMessage: 'This privacy request status change is not allowed from the current state.',
    action: 'Refresh the request and choose a valid action.',
    retryable: false,
    exposure: 'public',
  },
  PRIVACY_REQUEST_STATE_CONFLICT: {
    status: 409,
    category: 'conflict',
    userMessage: 'The privacy request changed before this action completed.',
    action: 'Refresh the request and try again.',
    retryable: true,
    exposure: 'public',
  },
  PRIVACY_EXPORT_NOT_READY: {
    status: 409,
    category: 'conflict',
    userMessage: 'This export is not ready to download yet.',
    retryable: true,
    exposure: 'public',
  },
  PRIVACY_EXPORT_EXPIRED: {
    status: 410,
    category: 'not_found',
    userMessage: 'This export has expired and is no longer available.',
    action: 'Generate a new export.',
    retryable: false,
    exposure: 'public',
  },
  PRIVACY_EXPORT_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'The requested export could not be found.',
    retryable: false,
    exposure: 'public',
  },
  PRIVACY_EXPORT_PREREQUISITES_NOT_MET: {
    status: 409,
    category: 'conflict',
    userMessage:
      'This request must complete identity verification and be in Processing status before an export can be generated.',
    action: 'Verify identity and move the request to Processing, then try again.',
    retryable: false,
    exposure: 'public',
  },
  PRIVACY_ERASURE_PREREQUISITES_NOT_MET: {
    status: 409,
    category: 'conflict',
    userMessage:
      'This request must be an erasure request, complete identity verification, and be in Processing status before erasure can run.',
    action: 'Verify identity and move the request to Processing, then try again.',
    retryable: false,
    exposure: 'public',
  },
  PRIVACY_ERASURE_BLOCKED: {
    status: 409,
    category: 'conflict',
    userMessage: 'Erasure cannot proceed while blocking conditions remain unresolved.',
    action: 'Resolve the listed blocking conditions and try again.',
    retryable: false,
    exposure: 'public',
  },
  PRIVACY_ERASURE_EXECUTION_NOT_FOUND: {
    status: 404,
    category: 'not_found',
    userMessage: 'No erasure execution was found for this request.',
    retryable: false,
    exposure: 'public',
  },
} as const satisfies Record<string, ErrorDefinition>;

export type AppErrorCode = keyof typeof ERROR_REGISTRY;

export function isAppErrorCode(value: unknown): value is AppErrorCode {
  return typeof value === 'string' && value in ERROR_REGISTRY;
}
