apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: ServiceAccount
      name: opsknight-agent
    patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: opsknight-agent
      automountServiceAccountToken: true
  - target:
      kind: Deployment
      name: opsknight-agent
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: opsknight-agent
      spec:
        template:
          spec:
            automountServiceAccountToken: true
