apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - deployment.yaml
  - service.yaml
  - pod-disruption-budget.yaml

images:
  - name: ghcr.io/opsknight-labs/opsknight
    newTag: 1.4.0
