apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opsknight-app-pdb
  namespace: opsknight
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: opsknight-app
      opsknight-role: integrated
